services:
  api:
    container_name: dividai-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    env_file:
        - .env
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - database
      - redis
  database:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
     - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
